[tox]
env_list =
    lint
    type
    py{310,311,312,313,314}

[testenv]
description = run tests
deps =
    pytest
commands =
    pytest {posargs:tests}

[testenv:lint]
description = format and lint
skip_install = true
deps =
    ruff
commands =
    ruff format .
    ruff check --fix .

[testenv:type]
description = run type check
skip_install = true
deps =
    mypy
commands =
    mypy --install-types --non-interactive --ignore-missing-imports torch_frft/ tests/

[testenv:py310]
basepython = python3.10

[testenv:py311]
basepython = python3.11

[testenv:py312]
basepython = python3.12

[testenv:py313]
basepython = python3.13

[testenv:py314]
basepython = python3.14
description = Run tests and code coverage
passenv = *
deps =
    codecov
    pytest
    pytest-cov
commands =
    pytest --cov=./ --cov-append --cov-report=xml {posargs:tests}
    codecov -e TOXENV

[gh-actions]
python =
    3.10: py310
    3.11: py311
    3.12: py312
    3.13: py313
    3.14: py314, lint, type
